//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BabyShop.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organization
    {
        public int PostId { get; set; }
        public int TovarId { get; set; }
        public Nullable<int> CityId { get; set; }
        public string kolvo { get; set; }
        public Nullable<int> AccepterTheOrder { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    
        public virtual City City { get; set; }
        public virtual User User { get; set; }
        public virtual Post Post { get; set; }
        public virtual Tovar Tovar { get; set; }
    }
}
