//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BabyShop.Model.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales
    {
        public int Id { get; set; }
        public Nullable<int> TovarId { get; set; }
        public string Kolvo { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> RegularPeopleId { get; set; }
    
        public virtual RegularPeople RegularPeople { get; set; }
        public virtual Tovar Tovar { get; set; }
    }
}
